"""
MuMu Configuration (Auto-generated by mumu_calibration.py)
"""

# MuMu window position and size (in pixels)
# Generated on: mumu_calibration.py

MUMU_WINDOW_POS = (1383, 41)      # Top-left corner (x, y)
MUMU_WINDOW_SIZE = (534, 985)     # Width, Height

# For use with MuMuAdapter:
# adapter = MuMuAdapter(window_pos=MUMU_WINDOW_POS, window_size=MUMU_WINDOW_SIZE)
